# Plugin Information
pluginGroup=dev.dong4j.zeka.stack
pluginName=IntelliAI Repairer
pluginVersion=2025.3.1300
# IntelliAI Engine \u63D2\u4EF6\u7248\u672C\u53F7\uFF08\u7EDF\u4E00\u7BA1\u7406\uFF0C\u907F\u514D\u91CD\u590D\uFF09
engineVersion=2025.3.1200
kitVersion=2025.3.1200
checkstyleIdeaVersion=26.0.0
rootProjectName=intelli-ai-repairer

# IntelliJ Platform Configuration
platformType=IC
#platformVersion=2024.2
platformVersion=2025.2
platformSinceBuild=242.0
platformUntilBuild=253.*

# Java Configuration
javaVersion=21

# Publishing Configuration

org.gradle.jvmargs=-Xms1g -Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
