server {
    listen 80;
    server_name tra.dong4j.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name tra.dong4j.site;

    ssl_certificate /etc/nginx/encrypt/fullchain.pem;
    ssl_certificate_key /etc/nginx/encrypt/privkey.pem;

    root /var/www/tra-landing;
    index landing.html;

    location = / {
        try_files /landing.html =404;
    }

    location = /tra.zip {
        root /var/www/tra-landing;
        types { application/zip zip; }
        add_header Content-Disposition 'attachment; filename="tra.zip"';
    }

    location /docs {
        alias /var/www/tra-docs/;
        index index.html;
        try_files $uri $uri/ /guide/index.html;
    }
}

