server {
    # 监听 HTTP 并重定向到 HTTPS
    listen 80;
    server_name aij.dong4j.site;
    return 301 https://$host$request_uri;
}

server {
    # 监听 HTTPS
    listen 443 ssl http2;
    server_name aij.dong4j.site;

    # SSL 配置
    ssl_certificate /etc/nginx/encrypt/fullchain.pem;
    ssl_certificate_key /etc/nginx/encrypt/privkey.pem;

    # 静态页面目录（确保 landing.html 在此路径下）
    root /var/www/aij-landing;
    index landing.html;

    # 根路径访问时直接返回 landing.html
    location = / {
        try_files /landing.html =404;
    }
    
    location = /aij.zip {
        root /var/www/aij-landing;
        types { application/zip zip; }
        add_header Content-Disposition 'attachment; filename="aij.zip"';
    }

    # 用户手册文档 (Docsify)
    location /docs {
        alias /var/www/aij-docs/;
        index index.html;
        try_files $uri $uri/ /guide/index.html;
    }

}