#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import {fileURLToPath} from 'url';

// 获取当前目录
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 获取项目根目录 (webview 的父目录)
const projectRoot = path.resolve(__dirname, '../..');
const gradlePropertiesPath = path.join(projectRoot, 'gradle.properties');
const buildGradlePath = path.join(projectRoot, 'build.gradle');
const buildGradleKtsPath = path.join(projectRoot, 'build.gradle.kts');

let version = null;

// 优先从 gradle.properties 中读取 pluginVersion
if (fs.existsSync(gradlePropertiesPath)) {
  const propertiesContent = fs.readFileSync(gradlePropertiesPath, 'utf8');
  const match = propertiesContent.match(/^pluginVersion=(.+)$/m);
  if (match) {
    version = match[1].trim();
  }
}

// fallback: build.gradle
if (!version && fs.existsSync(buildGradlePath)) {
  const buildGradleContent = fs.readFileSync(buildGradlePath, 'utf8');
  let versionMatch = buildGradleContent.match(/^version\s*=\s*'(.+)'$/m);
  if (!versionMatch) {
    const lines = buildGradleContent.split('\n');
    const versionLine = lines.find(line => line.trim().startsWith('version ='));
    if (versionLine) {
      const match = versionLine.match(/version\s*=\s*'(.+)'/);
      if (match) {
        versionMatch = match;
      }
    }
  }
  if (versionMatch) {
    version = versionMatch[1].trim();
  }
}

// fallback: build.gradle.kts (try to read pluginVersion from properties if referenced)
if (!version && fs.existsSync(buildGradleKtsPath)) {
  const buildGradleContent = fs.readFileSync(buildGradleKtsPath, 'utf8');
  const versionLine = buildGradleContent.split('\n').find(line => line.trim().startsWith('version'));
  if (versionLine) {
    const match = versionLine.match(/version\s*=\s*["'](.+)["']/);
    if (match) {
      version = match[1].trim();
    }
  }
}

if (!version) {
  console.error('Error: Could not find version in gradle.properties/build.gradle');
  process.exit(1);
}
console.log(`Found version: ${version}`);

// 创建版本文件供 webview 使用
const versionDir = path.join(__dirname, '../src/version');
if (!fs.existsSync(versionDir)) {
  fs.mkdirSync(versionDir, { recursive: true });
}

const versionFilePath = path.join(versionDir, 'version.ts');
const versionFileContent = `// Auto-generated version file
// This file is automatically generated during the build process
// Do not edit manually

export const APP_VERSION = '${version}';
`;

fs.writeFileSync(versionFilePath, versionFileContent);
console.log(`Version file created at: ${versionFilePath}`);
